### ISSUE TITLE
SSSP emin bug?

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [GraphBLAS/LAGraph#174] opened 2023-03-22 20:02 UTC
There seems to be an issue with SSSP, regarding the need to compute emin first.  See #170

**Comment by szarnyasg** [comment] 2023-03-22 23:31
I managed to reproduce the issue. However, it is a Heisenbug and only occurs sometimes with a <50% probability.

To initialize the reproduction branch and download the required data files, run:

```bash
git clone --branch sssp-emin-reproduction https://github.com/szarnyasg/LAGraph
cd LAGraph
cd data
./dl-datagen-data-set.sh
cd ..
```

I use [`numdiff`](https://www.nongnu.org/numdiff/) (available in `apt`/`brew`) for comparing the reference output and LAGraph's output.

Here's what I do for repeated runs:

```bash
make library
for i in `seq 1 10`; do
  build/src/test/test_SingleSourceShortestPath
  numdiff --absolute-tolerance 0.00001 sssp-output.txt data/datagen-7_5-fb-sssp.txt
done
```

The output of the commands in the loop is here:
https://gist.github.com/szarnyasg/1d52dd52f56e87b655f4e64519dafd6e

In this case, there were 4 failures and 6 passes out of 10 executions.

**Comment by szarnyasg** [comment] 2023-03-22 23:39
Adding `LAGraph_Cached_EMin(G, msg);` indeed makes no difference – that tricked me because I did not think of having encountered a Heisenberg when testing this.

I ran the experiments above on MacOS using an M1 Max CPU and Clang 14. When moving to a cloud server (Ubuntu 22.04, Xeon Cascade Lake CPU cores, GCC 11.3), I see other weird behaviour: the loading seems to get stuck. Strange. Anyways, I'm calling it a day now.

**Comment by szarnyasg** [comment] 2023-03-25 21:10
(This issue was discussed in depth via emails – I'm copying my input for the discussion for future reference):

Based on my investigation, the problem is restricted to multi-threaded execution on Arm CPUs.

- I could reproduce the problem on Apple Silicon (M1 Max), Amazon's Graviton 2 (AWS EC2 c6g.16xlarge instance), and Graviton 3 (AWS EC2 c7g.8xlarge instance).

- I could *not* reproduce it on x86, including various Xeons (both ones from 2013 in our cluster and new ones in AWS) and AMD EPYCs (in AWS).

The problem itself is really subtle. Even when it occurs, it only affects 1-2 out of the 633,432 results (the number of nodes in an LDBC graph). The differences are approximately between 0.001 and 0.1 but of course they are way larger than rounding errors would be. Here's a typical case of the results being different:

```
$ numdiff --absolute-tolerance 0.00001 sssp-output-{0,2}.txt
----------------
##317087  #:1   <== 3.52419000e+00
##317087  #:1   ==> 3.63057000e+00
@ Absolute error = 1.0638000000e-1, Relative error = 3.0185659684e-2
----------------
##329554  #:1   <== 3.45130000e+00
##329554  #:1   ==> 3.48370000e+00
@ Absolute error = 3.2400000000e-2, Relative error = 9.3877669284e-3

+++  File "sssp-output-0.txt" differs from file "sssp-output-2.txt"
```

On Graviton 3 CPUs, the bug is easier to reproduce than on M1 and Graviton 2. Using Graviton 3, I get incorrect results approx. 64% of the time. On the others, this probability is <25%.

I have a branch to reproduce the issue:
https://github.com/szarnyasg/LAGraph/tree/sssp-emin-reproduction

```
git clone --branch sssp-emin-reproduction https://github.com/szarnyasg/LAGraph
cd LAGraph
cd data
./dl-datagen-data-set.sh
cd ..
make library
build/src/test/test_SingleSourceShortestPath
time md5sum sssp-output* | sort | cut -d' ' -f1 | uniq -c | sort -nr > md5sums
head md5sums
```

**Comment by szarnyasg** [comment] 2023-03-25 22:23
This was resolved via https://github.com/DrTimothyAldenDavis/GraphBLAS/pull/209.

**Closed as completed by szarnyasg** 2023-03-25 22:23 UTC
