### ISSUE TITLE
Build fails setting when selecting vanilla

### ISSUE THREAD

**Issue by mcordery** [GraphBLAS/LAGraph#155] opened 2022-12-22 19:08 UTC
So, trying to build with a custom version of GraphBLAS  that doesn't have every GxB extension yet so I'm trying to build with LAGRAPH_VANILLA=1. I had problems with this on my end so I thought I'd see if I could build LAGraph with the reference GraphBLAS to see if I could figure out if I was doing something wrong but I'm still getting errors on the build.

So, config and build as follows

export CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=/home/mcordery/lagraph/LAGraph/lag -DLAGRAPH_VANILLA=1"
make

This kicks off the vanilla build correctly but hit's at least one error

In file included from /home/mcordery/lagraph/LAGraph/include/LAGraph.h:49:0,
                 from /home/mcordery/lagraph/LAGraph/src/utility/LG_internal.h:26,
                 from /home/mcordery/lagraph/LAGraph/src/algorithm/LG_BreadthFirstSearch_SSGrB.c:45:
/home/mcordery/lagraph/LAGraph/src/algorithm/LG_BreadthFirstSearch_SSGrB.c: In function ‘LG_BreadthFirstSearch_SSGrB’:
/home/mcordery/lagraph/LAGraph/src/algorithm/LG_BreadthFirstSearch_SSGrB.c:34:16: error: ‘w’ undeclared (first use in this function)
     GrB_free (&w) ;         \
                ^

As I was trying to work around this with our version (that has all of the GrB routines and probably 99% of the GxB stuff) I kept hitting issues where the code or the tests or the demos were trying to use GxB routines, esp from the experimental/ directory

**Comment by mcordery** [comment] 2022-12-22 21:59
This seems to be an issue with compilers not picking up #if LAGRAPH_SUITESPARSE or #if !LAGRAPH_SUITESPARSE but can be fixed with setting #if defined(LAGRAPH_SUITESPARSE) or #if !defined(LAGRAPH_SUITESPARSE) where compilation errors occur, but this doesn't catch all of them so a fair number of tests fail.

**Comment by jamesETsmith** [comment] 2022-12-26 19:10
### Reproducing the Problem
I'm seeing the same errors building against our own GraphBLAS implementation:
```shell
cmake -S . -B build -DGRAPHBLAS_ROOT=/home/james/apps/LucataGraphBLAS/build/src/lib/libLucataGraphBLAS.a -DGRAPHBLAS_INCLUDE_DIR=/home/james/apps/LucataGraphBLAS/include -DLAGRAPH_VANILLA=1
cmake --build build --parallel 6
```

and building against the reference GraphBLAS implementation with
```shell
cmake -S . -B build -DLAGRAPH_VANILLA=1
cmake --build build --parallel 6
```

Both result in compile failures:
```shell
In file included from /home/james/apps/LAGraph/include/LAGraph.h:49,
                 from /home/james/apps/LAGraph/src/utility/LG_internal.h:26,
                 from /home/james/apps/LAGraph/src/algorithm/LG_BreadthFirstSearch_SSGrB.c:45:
/home/james/apps/LAGraph/src/algorithm/LG_BreadthFirstSearch_SSGrB.c: In function ‘LG_BreadthFirstSearch_SSGrB’:
/home/james/apps/LAGraph/src/algorithm/LG_BreadthFirstSearch_SSGrB.c:34:16: error: ‘w’ undeclared (first use in this function)
   34 |     GrB_free (&w) ;         \
...
...
```

### Identifying the Problem
This problem is caused by `LA_ASSERT` calling `FREE_ALL` when several of the variables have not been declared. Here are some of the key code blocks:

https://github.com/GraphBLAS/LAGraph/blob/81a0a7783fed8eaab41111abab7a33925a68f0d8/src/algorithm/LG_BreadthFirstSearch_SSGrB.c#L61-L62

https://github.com/GraphBLAS/LAGraph/blob/81a0a7783fed8eaab41111abab7a33925a68f0d8/src/utility/LG_internal.h#L180-L188

https://github.com/GraphBLAS/LAGraph/blob/81a0a7783fed8eaab41111abab7a33925a68f0d8/src/algorithm/LG_BreadthFirstSearch_SSGrB.c#L38-L42

**Comment by DrTimothyAldenDavis** [comment] 2022-12-26 22:09
Thanks for catching this.  I hadn't tested the vanilla case for a while, since LAGraph requires the GxB_Type* query methods and so for now, can't use a pure GraphBLAS without that particular GxB extension.  But the vanilla case should work anyway, even if using SuiteSparse:GraphBLAS.

**Comment by DrTimothyAldenDavis** [comment] 2022-12-26 23:18
The vanilla case can be revised so that LAGraph compiles, but most of the methods will fail because the LAGraph_*_TypeName methods are required by many LAGraph methods, and those require the ability to query the type of a matrix, vector, or scalar.  That can only be done with the GxB methods in SuiteSparse:GrapBLAS.

So what I've done is to disable the "#ifdef LAGRAPH_SUITESPARSE" in src/utility/LAGraph_TypeName.c.  This allows LAGraph to work, but it requires the "vanilla" GraphBLAS to implement the GxB_Matrix_TypeName, GxB_Vector_TypeName, and GxB_Scalar_TypeName methods.

The LAGraph development group decided that those 3 methods were essential, and that LAGraph can't work without them.  In the long term, they will be added to the v2.1 C API Specification as "GrB_Matrix_get" (for example).

I'll post an updated v1.0.1 draft on the dev branch shortly.

**Comment by DrTimothyAldenDavis** [comment] 2022-12-26 23:26
Try https://github.com/GraphBLAS/LAGraph/releases/tag/v1.0.1.beta1 .  It should be fixed.

Some tests are skipped, such as all "brutal" tests (requires GraphBLAS to be given pointers to malloc/calloc/realloc/free).  The tests for lcc, msf, and scc are also skipped, since those methods require SuiteSparse:GraphBLAS.

**Comment by mcordery** [comment] 2022-12-28 18:32
Thanks!

**Comment by mcordery** [comment] 2022-12-28 23:20
Interestingly, I still hit a problem compiling LAGraph_FastGraphletTransform.c (when trying to build our with our library) due to GxB_Matrix_split and GxB_Iterator stuff. I only grabbed the dev branch so is that something fixed in the tagged branch? Just wondering if we're missing something in our GraphBLAS.h file.

**Comment by DrTimothyAldenDavis** [comment] 2022-12-29 02:31
Oops.  It seems I missed that.  The experimental/ side of LAGraph is not as
polished as the src/ side.

The KCore methods also use GxB, like "GxB_ANY_SECONDI_INT64" in
LAGraph_KCoreDecompose.c.

**Comment by DrTimothyAldenDavis** [comment] 2022-12-29 02:40
I don't have a good way to test this, to make sure no GxB slips through.  I would need to compile SuiteSparse:GraphBLAS without any GxB methods or objects (except for GxB_Matrix_typename).  That's not infeasible ... I have a way to rename all of SuiteSparse:GraphBLAS already.  I have to do it for the MATLAB interface, since SuiteSparse:GraphBLAS is already built into MATLAB (with an older version than my current one).  So for my own MATLAB interface to GraphBLAS, I rename everything: https://github.com/DrTimothyAldenDavis/GraphBLAS/tree/stable/GraphBLAS/rename .

I would need to do something similar for the libgraphblas.so that I build.

**Comment by DrTimothyAldenDavis** [comment] 2022-12-29 02:44
Try the latest commit to the dev branch.

**Comment by mcordery** [comment] 2022-12-30 01:38
Great stuff now Tim. After your latest updates we can now completely build a vanilla version (after I fixed a couple of things on our end that were for some reason named in a way that did NOT match the GrB versions. I think they must have gotten made ages ago and no one noticed since it was all hidden away and we were focusing on getting ourselves up to the 1.3 and then the 2.0 spec. At this point I just have to get the C++ libraries linked in

**Comment by DrTimothyAldenDavis** [comment] 2022-12-30 01:50
Great!  Glad to be of help.

**Closed as completed by DrTimothyAldenDavis** 2022-12-30 01:50 UTC

**Comment by mcordery** [comment] 2022-12-30 01:51
Minor correction, I noticed we picked up our include path but not our library but it looks like what we're missing is mostly links to C++ lib stuff but  thanks again. :-)
